# Generated by Django 5.1.4 on 2025-02-03 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_yn', models.BooleanField(default=True, verbose_name='사용여부')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일시')),
                ('modi_dtm', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('name', models.CharField(max_length=100, verbose_name='부서명')),
                ('sort_number', models.IntegerField(null=True, verbose_name='정렬순서')),
                ('modi_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modi', to=settings.AUTH_USER_MODEL, verbose_name='수정유저')),
                ('reg_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_reg', to=settings.AUTH_USER_MODEL, verbose_name='등록유저')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_yn', models.BooleanField(default=True, verbose_name='사용여부')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일시')),
                ('modi_dtm', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('title', models.CharField(max_length=100, verbose_name='벤더명')),
                ('modi_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modi', to=settings.AUTH_USER_MODEL, verbose_name='수정유저')),
                ('reg_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_reg', to=settings.AUTH_USER_MODEL, verbose_name='등록유저')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_yn', models.BooleanField(default=True, verbose_name='사용여부')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일시')),
                ('modi_dtm', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('status', models.CharField(max_length=50, verbose_name='상태')),
                ('modi_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modi', to=settings.AUTH_USER_MODEL, verbose_name='수정유저')),
                ('reg_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_reg', to=settings.AUTH_USER_MODEL, verbose_name='등록유저')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_yn', models.BooleanField(default=True, verbose_name='사용여부')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일시')),
                ('modi_dtm', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('code', models.CharField(max_length=10, verbose_name='매장코드')),
                ('name', models.CharField(max_length=100, verbose_name='매장명')),
                ('sort_number', models.IntegerField(null=True, verbose_name='정렬순서')),
                ('modi_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modi', to=settings.AUTH_USER_MODEL, verbose_name='수정유저')),
                ('reg_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_reg', to=settings.AUTH_USER_MODEL, verbose_name='등록유저')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_yn', models.BooleanField(default=True, verbose_name='사용여부')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일시')),
                ('modi_dtm', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('from_work_date', models.DateField(null=True)),
                ('to_work_date', models.DateField(null=True)),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('modi_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modi', to=settings.AUTH_USER_MODEL, verbose_name='수정유저')),
                ('reg_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_reg', to=settings.AUTH_USER_MODEL, verbose_name='등록유저')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_yn', models.BooleanField(default=True, verbose_name='사용여부')),
                ('reg_dtm', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록일시')),
                ('modi_dtm', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('invoice_name', models.CharField(max_length=255, verbose_name='인보이스명')),
                ('invoice_number', models.CharField(max_length=100, unique=True, verbose_name='인보이스번호')),
                ('invoice_issue_date', models.DateField(verbose_name='인보이스날짜')),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='총금액')),
                ('invoice_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='인보이스 파일 URL')),
                ('invoice_thumb_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='인보이스 썸네일 경로')),
                ('sort_number', models.IntegerField(null=True, verbose_name='정렬순서')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amount_entry.department', verbose_name='부서 ID')),
                ('modi_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modi', to=settings.AUTH_USER_MODEL, verbose_name='수정유저')),
                ('reg_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_reg', to=settings.AUTH_USER_MODEL, verbose_name='등록유저')),
                ('invoice_vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amount_entry.invoicevendor', verbose_name='인보이스 벤더 ID')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amount_entry.status', verbose_name='상태 ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amount_entry.store', verbose_name='매장 ID')),
                ('work_schd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amount_entry.workschedule', verbose_name='스케줄 ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
